import { type NextRequest, NextResponse } from "next/server"

// Gemini API endpoint for the 2.0-flash model
const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
const API_KEY = "AIzaSyAG3hpw2yL_6zwN4yJVoeSuomwrp1s_-CU"

// List of legal-related keywords to check if a query is legal in nature
const legalKeywords = [
  "law",
  "legal",
  "right",
  "rights",
  "court",
  "judge",
  "lawyer",
  "attorney",
  "lawsuit",
  "sue",
  "plaintiff",
  "defendant",
  "contract",
  "agreement",
  "tenant",
  "landlord",
  "rent",
  "lease",
  "property",
  "divorce",
  "custody",
  "alimony",
  "will",
  "testament",
  "inheritance",
  "heir",
  "crime",
  "criminal",
  "felony",
  "misdemeanor",
  "arrest",
  "police",
  "jail",
  "prison",
  "bail",
  "parole",
  "probation",
  "sentence",
  "conviction",
  "appeal",
  "statute",
  "regulation",
  "legislation",
  "act",
  "bill",
  "constitution",
  "amendment",
  "liability",
  "negligence",
  "damages",
  "compensation",
  "injury",
  "accident",
  "insurance",
  "claim",
  "settlement",
  "dispute",
  "arbitration",
  "mediation",
  "hearing",
  "trial",
  "verdict",
  "judgment",
  "injunction",
  "restraining order",
  "eviction",
  "foreclosure",
  "bankruptcy",
  "debt",
  "creditor",
  "debtor",
  "tax",
  "irs",
  "audit",
  "patent",
  "trademark",
  "copyright",
  "intellectual property",
  "employment",
  "termination",
  "discrimination",
  "harassment",
  "wage",
  "salary",
  "overtime",
  "benefit",
  "pension",
  "retirement",
  "social security",
  "disability",
  "immigration",
  "visa",
  "citizenship",
  "deportation",
  "asylum",
  "refugee",
  "marriage",
  "divorce",
  "prenuptial",
  "postnuptial",
  "child support",
  "custody",
  "visitation",
  "adoption",
  "guardianship",
  "power of attorney",
  "notary",
  "affidavit",
  "testimony",
  "witness",
  "evidence",
  "discovery",
  "deposition",
  "subpoena",
  "warrant",
  "search",
  "seizure",
  "miranda",
  "rights",
  "fifth amendment",
  "fourth amendment",
  "first amendment",
  "due process",
  "equal protection",
  "civil rights",
  "human rights",
  "consumer rights",
  "lemon law",
  "class action",
  "malpractice",
  "ethics",
  "bar association",
  "license",
  "permit",
  "zoning",
  "ordinance",
  "bylaw",
  "regulation",
  "compliance",
  "violation",
  "penalty",
  "fine",
  "sanction",
  "ipc",
  "section",
  "article",
  "clause",
  "provision",
  "term",
  "condition",
  "fir",
  "complaint",
  "petition",
  "motion",
  "brief",
  "pleading",
  "filing",
  "docket",
  "case",
  "precedent",
  "jurisprudence",
  "doctrine",
  "theory",
  "principle",
  "rule",
  "standard",
  "guideline",
  "procedure",
  "process",
  "protocol",
  "formality",
  "technicality",
  "loophole",
  "exception",
  "exemption",
  "waiver",
  "consent",
  "authorization",
  "permission",
  "approval",
  "denial",
  "rejection",
  "acceptance",
  "offer",
  "consideration",
  "breach",
  "default",
  "remedy",
  "relief",
  "restitution",
  "specific performance",
  "injunctive relief",
  "declaratory relief",
  "punitive damages",
  "compensatory damages",
  "actual damages",
  "nominal damages",
  "liquidated damages",
  "statutory damages",
  "treble damages",
  "exemplary damages",
  "consequential damages",
  "incidental damages",
  "special damages",
  "general damages",
  "economic damages",
  "non-economic damages",
  "pain and suffering",
  "emotional distress",
  "mental anguish",
  "loss of consortium",
  "loss of companionship",
  "loss of enjoyment",
  "loss of use",
  "loss of profit",
  "lost wages",
  "medical expenses",
  "legal fees",
  "attorney fees",
  "court costs",
  "filing fees",
  "service fees",
  "expert witness fees",
  "deposition costs",
  "transcript costs",
  "appeal costs",
  "bond",
  "surety",
  "guarantor",
  "indemnity",
  "indemnification",
  "hold harmless",
  "release",
  "waiver",
  "disclaimer",
  "limitation of liability",
  "exculpatory clause",
  "force majeure",
  "act of god",
  "impossibility",
  "impracticability",
  "frustration of purpose",
  "mutual mistake",
  "unilateral mistake",
  "fraud",
  "misrepresentation",
  "concealment",
  "non-disclosure",
  "duress",
  "undue influence",
  "unconscionability",
  "illegality",
  "public policy",
  "void",
  "voidable",
  "rescission",
  "reformation",
  "modification",
  "amendment",
  "addendum",
  "codicil",
  "supplement",
  "exhibit",
  "attachment",
  "incorporation by reference",
  "merger clause",
  "integration clause",
  "severability clause",
  "choice of law",
  "forum selection",
  "jurisdiction",
  "venue",
  "service of process",
  "summons",
  "complaint",
  "answer",
  "reply",
  "counterclaim",
  "cross-claim",
  "third-party claim",
  "impleader",
  "interpleader",
  "intervention",
  "joinder",
  "consolidation",
  "severance",
  "bifurcation",
  "stay",
  "continuance",
  "extension",
  "tolling",
  "statute of limitations",
  "laches",
  "estoppel",
  "waiver",
  "res judicata",
  "collateral estoppel",
  "law of the case",
  "stare decisis",
  "precedent",
  "overrule",
  "distinguish",
  "reconcile",
  "harmonize",
  "interpret",
  "construe",
  "construction",
  "plain meaning",
  "ambiguity",
  "vagueness",
  "overbreadth",
  "under-inclusiveness",
  "strict scrutiny",
  "intermediate scrutiny",
  "rational basis",
  "balancing test",
  "totality of circumstances",
  "reasonable person",
  "reasonable doubt",
  "preponderance of evidence",
  "clear and convincing evidence",
  "beyond a reasonable doubt",
  "prima facie",
  "burden of proof",
  "shifting burden",
  "presumption",
  "inference",
  "judicial notice",
  "administrative notice",
  "official notice",
  "judicial review",
  "administrative review",
  "appellate review",
  "de novo review",
  "abuse of discretion",
  "clearly erroneous",
  "substantial evidence",
  "harmless error",
  "plain error",
  "fundamental error",
  "structural error",
  "reversible error",
  "remand",
  "vacate",
  "reverse",
  "affirm",
  "modify",
  "dismiss",
  "with prejudice",
  "without prejudice",
  "nol pros",
  "nolle prosequi",
  "plea bargain",
  "plea agreement",
  "guilty plea",
  "not guilty plea",
  "no contest plea",
  "nolo contendere",
  "allocution",
  "sentencing",
  "minimum sentence",
  "maximum sentence",
  "mandatory sentence",
  "discretionary sentence",
  "determinate sentence",
  "indeterminate sentence",
  "concurrent sentence",
  "consecutive sentence",
  "suspended sentence",
  "probation",
  "parole",
  "supervised release",
  "community service",
  "restitution",
  "fine",
  "forfeiture",
  "seizure",
  "confiscation",
  "eminent domain",
  "taking",
  "just compensation",
  "condemnation",
  "inverse condemnation",
  "regulatory taking",
  "physical taking",
  "easement",
  "right of way",
  "encroachment",
  "trespass",
  "nuisance",
  "attractive nuisance",
  "premises liability",
  "slip and fall",
  "trip and fall",
  "negligence",
  "gross negligence",
  "willful and wanton",
  "reckless",
  "intentional",
  "strict liability",
  "product liability",
  "design defect",
  "manufacturing defect",
  "failure to warn",
  "inadequate warning",
  "misuse",
  "alteration",
  "modification",
  "assumption of risk",
  "contributory negligence",
  "comparative negligence",
  "last clear chance",
  "rescue doctrine",
  "good samaritan",
  "duty to rescue",
  "duty of care",
  "standard of care",
  "breach of duty",
  "causation",
  "proximate cause",
  "but for cause",
  "intervening cause",
  "superseding cause",
  "foreseeability",
  "eggshell skull",
  "thin skull",
  "res ipsa loquitur",
  "negligence per se",
  "statutory violation",
  "regulatory violation",
  "administrative violation",
  "civil violation",
  "criminal violation",
  "infraction",
  "citation",
  "ticket",
  "summons",
  "arraignment",
  "indictment",
  "information",
  "grand jury",
  "petit jury",
  "jury selection",
  "voir dire",
  "challenge for cause",
  "peremptory challenge",
  "jury instructions",
  "jury deliberation",
  "jury verdict",
  "hung jury",
  "mistrial",
  "directed verdict",
  "judgment as a matter of law",
  "judgment notwithstanding the verdict",
  "jnov",
  "new trial",
  "remittitur",
  "additur",
  "settlement",
  "settlement conference",
  "pretrial conference",
  "status conference",
  "case management conference",
  "discovery",
  "initial disclosure",
  "mandatory disclosure",
  "request for production",
  "request for admission",
  "interrogatory",
  "deposition",
  "oral deposition",
  "written deposition",
  "subpoena",
  "subpoena duces tecum",
  "motion to compel",
  "motion to quash",
  "protective order",
  "confidentiality order",
  "sealing order",
  "gag order",
  "temporary restraining order",
  "preliminary injunction",
  "permanent injunction",
  "declaratory judgment",
  "summary judgment",
  "partial summary judgment",
  "judgment on the pleadings",
  "motion to dismiss",
  "demurrer",
  "failure to state a claim",
  "lack of jurisdiction",
  "improper venue",
  "forum non conveniens",
  "choice of law",
  "conflict of laws",
  "full faith and credit",
  "comity",
  "reciprocity",
  "extradition",
  "rendition",
  "removal",
  "remand",
  "diversity jurisdiction",
  "federal question",
  "supplemental jurisdiction",
  "ancillary jurisdiction",
  "pendent jurisdiction",
  "subject matter jurisdiction",
  "personal jurisdiction",
  "in personam jurisdiction",
  "in rem jurisdiction",
  "quasi in rem jurisdiction",
  "long-arm statute",
  "minimum contacts",
  "purposeful availment",
  "stream of commerce",
  "general jurisdiction",
  "specific jurisdiction",
  "tag jurisdiction",
  "consent jurisdiction",
  "waiver of jurisdiction",
  "sovereign immunity",
  "eleventh amendment immunity",
  "qualified immunity",
  "absolute immunity",
  "prosecutorial immunity",
  "judicial immunity",
  "legislative immunity",
  "executive immunity",
  "diplomatic immunity",
  "immunity from suit",
  "immunity from liability",
  "immunity from damages",
  "immunity from injunction",
  "immunity from specific performance",
  "immunity from declaratory relief",
  "immunity from discovery",
  "immunity from testimony",
  "immunity from production",
  "immunity from disclosure",
  "privilege",
  "attorney-client privilege",
  "work product doctrine",
  "deliberative process privilege",
  "executive privilege",
  "state secrets privilege",
  "official information privilege",
  "law enforcement privilege",
  "informant's privilege",
  "self-incrimination privilege",
  "spousal privilege",
  "marital communications privilege",
  "doctor-patient privilege",
  "psychotherapist-patient privilege",
  "clergy-penitent privilege",
  "journalist's privilege",
  "academic freedom privilege",
  "peer review privilege",
  "trade secret privilege",
  "bank secrecy",
  "tax return privacy",
  "census confidentiality",
  "juvenile record confidentiality",
  "adoption record confidentiality",
  "grand jury secrecy",
  "settlement negotiation confidentiality",
  "mediation confidentiality",
  "alternative dispute resolution",
  "adr",
  "mediation",
  "arbitration",
  "negotiation",
  "conciliation",
  "facilitation",
  "neutral evaluation",
  "mini-trial",
  "summary jury trial",
  "private judging",
  "rent-a-judge",
  "special master",
  "referee",
  "hearing officer",
  "administrative law judge",
  "alj",
  "immigration judge",
  "bankruptcy judge",
  "magistrate judge",
  "district judge",
  "circuit judge",
  "supreme court justice",
  "chief justice",
  "associate justice",
  "en banc",
  "panel",
  "majority",
  "plurality",
  "concurrence",
  "dissent",
  "per curiam",
  "memorandum opinion",
  "published opinion",
  "unpublished opinion",
  "precedential",
  "non-precedential",
  "persuasive authority",
  "binding authority",
  "mandatory authority",
  "primary authority",
  "secondary authority",
  "treatise",
  "restatement",
  "model code",
  "uniform act",
  "uniform commercial code",
  "ucc",
  "model penal code",
  "model rules of professional conduct",
  "model rules of judicial conduct",
  "canons of ethics",
  "code of ethics",
  "professional responsibility",
  "malpractice",
  "negligence",
  "incompetence",
  "ineffective assistance of counsel",
  "conflict of interest",
  "disqualification",
  "recusal",
  "bias",
  "prejudice",
  "impartiality",
  "neutrality",
  "fairness",
  "due process",
  "procedural due process",
  "substantive due process",
  "equal protection",
  "fundamental right",
  "liberty interest",
  "property interest",
  "life interest",
  "privacy",
  "autonomy",
  "bodily integrity",
  "reproductive rights",
  "marriage equality",
  "free speech",
  "freedom of expression",
  "freedom of religion",
  "establishment clause",
  "free exercise clause",
  "separation of church and state",
  "freedom of assembly",
  "freedom of association",
  "freedom of the press",
  "freedom of information",
  "right to petition",
  "right to bear arms",
  "search and seizure",
  "warrant",
  "probable cause",
  "reasonable suspicion",
  "terry stop",
  "stop and frisk",
  "arrest",
  "miranda warning",
  "right to remain silent",
  "right to counsel",
  "right to speedy trial",
  "right to public trial",
  "right to jury trial",
  "right to confront witnesses",
  "right to compulsory process",
  "right against double jeopardy",
  "right against self-incrimination",
  "right against cruel and unusual punishment",
  "right to bail",
  "right to habeas corpus",
  "writ of habeas corpus",
  "writ of mandamus",
  "writ of prohibition",
  "writ of certiorari",
  "writ of error",
  "writ of attachment",
  "writ of execution",
  "writ of garnishment",
  "writ of replevin",
  "writ of possession",
  "writ of sequestration",
  "writ of ne exeat",
  "writ of quo warranto",
  "writ of coram nobis",
  "writ of audita querela",
  "writ of error coram vobis",
  "extraordinary writ",
  "prerogative writ",
  "common law writ",
  "statutory writ",
  "constitutional writ",
  "original jurisdiction",
  "appellate jurisdiction",
  "exclusive jurisdiction",
  "concurrent jurisdiction",
  "limited jurisdiction",
  "general jurisdiction",
  "special jurisdiction",
  "territorial jurisdiction",
  "extraterritorial jurisdiction",
  "universal jurisdiction",
  "admiralty jurisdiction",
  "maritime jurisdiction",
  "bankruptcy jurisdiction",
  "probate jurisdiction",
  "family law jurisdiction",
  "juvenile jurisdiction",
  "criminal jurisdiction",
  "civil jurisdiction",
  "administrative jurisdiction",
  "regulatory jurisdiction",
  "tax jurisdiction",
  "customs jurisdiction",
  "immigration jurisdiction",
  "naturalization jurisdiction",
  "patent jurisdiction",
  "trademark jurisdiction",
  "copyright jurisdiction",
  "antitrust jurisdiction",
  "securities jurisdiction",
  "environmental jurisdiction",
  "labor jurisdiction",
  "employment jurisdiction",
  "workers' compensation jurisdiction",
  "social security jurisdiction",
  "veterans benefits jurisdiction",
  "military jurisdiction",
  "court-martial jurisdiction",
  "tribal jurisdiction",
  "indian country jurisdiction",
  "state jurisdiction",
  "federal jurisdiction",
  "international jurisdiction",
  "transnational jurisdiction",
  "global jurisdiction",
  "cyberspace jurisdiction",
  "virtual jurisdiction",
  "digital jurisdiction",
  "electronic jurisdiction",
  "internet jurisdiction",
  "online jurisdiction",
  "e-commerce jurisdiction",
  "cloud computing jurisdiction",
  "data protection jurisdiction",
  "privacy jurisdiction",
  "cybersecurity jurisdiction",
  "information security jurisdiction",
  "national security jurisdiction",
  "homeland security jurisdiction",
  "intelligence jurisdiction",
  "counterintelligence jurisdiction",
  "counterterrorism jurisdiction",
  "war powers jurisdiction",
  "military commission jurisdiction",
  "enemy combatant jurisdiction",
  "prisoner of war jurisdiction",
  "geneva convention jurisdiction",
  "hague convention jurisdiction",
  "united nations jurisdiction",
  "international court of justice jurisdiction",
  "international criminal court jurisdiction",
  "world trade organization jurisdiction",
  "european union jurisdiction",
  "european court of human rights jurisdiction",
  "inter-american court of human rights jurisdiction",
  "african court on human and peoples' rights jurisdiction",
  "asean jurisdiction",
  "nafta jurisdiction",
  "usmca jurisdiction",
  "bilateral investment treaty jurisdiction",
  "multilateral investment treaty jurisdiction",
  "international investment arbitration jurisdiction",
  "international commercial arbitration jurisdiction",
  "international trade jurisdiction",
  "international finance jurisdiction",
  "international taxation jurisdiction",
  "international intellectual property jurisdiction",
  "international environmental jurisdiction",
  "international human rights jurisdiction",
  "international humanitarian law jurisdiction",
  "international criminal law jurisdiction",
  "international civil law jurisdiction",
  "international private law jurisdiction",
  "international public law jurisdiction",
  "international administrative law jurisdiction",
  "international regulatory law jurisdiction",
  "international constitutional law jurisdiction",
  "international customary law jurisdiction",
  "international treaty law jurisdiction",
  "international soft law jurisdiction",
  "international hard law jurisdiction",
  "international law of the sea jurisdiction",
  "international air law jurisdiction",
  "international space law jurisdiction",
  "international telecommunications law jurisdiction",
  "international internet law jurisdiction",
  "international cyber law jurisdiction",
  "international data law jurisdiction",
  "international privacy law jurisdiction",
  "international security law jurisdiction",
  "international peace and security jurisdiction",
  "international conflict resolution jurisdiction",
  "international dispute settlement jurisdiction",
  "international negotiation jurisdiction",
  "international mediation jurisdiction",
  "international arbitration jurisdiction",
  "international adjudication jurisdiction",
  "international enforcement jurisdiction",
  "international compliance jurisdiction",
  "international implementation jurisdiction",
  "international monitoring jurisdiction",
  "international verification jurisdiction",
  "international inspection jurisdiction",
  "international investigation jurisdiction",
  "international prosecution jurisdiction",
  "international defense jurisdiction",
  "international sentencing jurisdiction",
  "international punishment jurisdiction",
  "international rehabilitation jurisdiction",
  "international reintegration jurisdiction",
  "international reparation jurisdiction",
  "international compensation jurisdiction",
  "international restitution jurisdiction",
  "international satisfaction jurisdiction",
  "international guarantees of non-repetition jurisdiction",
  "international transitional justice jurisdiction",
  "international restorative justice jurisdiction",
  "international retributive justice jurisdiction",
  "international distributive justice jurisdiction",
  "international procedural justice jurisdiction",
  "international substantive justice jurisdiction",
  "international formal justice jurisdiction",
  "international informal justice jurisdiction",
  "international legal justice jurisdiction",
  "international social justice jurisdiction",
  "international economic justice jurisdiction",
  "international political justice jurisdiction",
  "international environmental justice jurisdiction",
  "international cultural justice jurisdiction",
  "international gender justice jurisdiction",
  "international racial justice jurisdiction",
  "international ethnic justice jurisdiction",
  "international religious justice jurisdiction",
  "international linguistic justice jurisdiction",
  "international age justice jurisdiction",
  "international disability justice jurisdiction",
  "international sexual orientation justice jurisdiction",
  "international gender identity justice jurisdiction",
  "international intersectional justice jurisdiction",
  "international multidimensional justice jurisdiction",
  "international comprehensive justice jurisdiction",
  "international holistic justice jurisdiction",
  "international integrated justice jurisdiction",
  "international coordinated justice jurisdiction",
  "international harmonized justice jurisdiction",
  "international synchronized justice jurisdiction",
  "international unified justice jurisdiction",
  "international consolidated justice jurisdiction",
  "international merged justice jurisdiction",
  "international combined justice jurisdiction",
  "international joint justice jurisdiction",
  "international shared justice jurisdiction",
  "international collective justice jurisdiction",
  "international collaborative justice jurisdiction",
  "international cooperative justice jurisdiction",
  "international mutual justice jurisdiction",
  "international reciprocal justice jurisdiction",
  "international bilateral justice jurisdiction",
  "international multilateral justice jurisdiction",
  "international regional justice jurisdiction",
  "international subregional justice jurisdiction",
  "international continental justice jurisdiction",
  "international intercontinental justice jurisdiction",
  "international hemispheric justice jurisdiction",
  "international global justice jurisdiction",
  "international universal justice jurisdiction",
  "international cosmic justice jurisdiction",
  "international natural justice jurisdiction",
  "international positive justice jurisdiction",
  "international normative justice jurisdiction",
  "international descriptive justice jurisdiction",
  "international prescriptive justice jurisdiction",
  "international analytical justice jurisdiction",
  "international synthetic justice jurisdiction",
  "international a priori justice jurisdiction",
  "international a posteriori justice jurisdiction",
  "international empirical justice jurisdiction",
  "international rational justice jurisdiction",
  "international intuitive justice jurisdiction",
  "international deductive justice jurisdiction",
  "international inductive justice jurisdiction",
  "international abductive justice jurisdiction",
  "international logical justice jurisdiction",
  "international illogical justice jurisdiction",
  "international reasonable justice jurisdiction",
  "international unreasonable justice jurisdiction",
  "international just justice jurisdiction",
  "international unjust justice jurisdiction",
  "international fair justice jurisdiction",
  "international unfair justice jurisdiction",
  "international equitable justice jurisdiction",
  "international inequitable justice jurisdiction",
  "international balanced justice jurisdiction",
  "international imbalanced justice jurisdiction",
  "international proportional justice jurisdiction",
  "international disproportional justice jurisdiction",
  "international appropriate justice jurisdiction",
  "international inappropriate justice jurisdiction",
  "international adequate justice jurisdiction",
  "international inadequate justice jurisdiction",
  "international sufficient justice jurisdiction",
  "international insufficient justice jurisdiction",
  "international complete justice jurisdiction",
  "international incomplete justice jurisdiction",
  "international perfect justice jurisdiction",
  "international imperfect justice jurisdiction",
  "international ideal justice jurisdiction",
  "international non-ideal justice jurisdiction",
  "international utopian justice jurisdiction",
  "international dystopian justice jurisdiction",
  "international realistic justice jurisdiction",
  "international unrealistic justice jurisdiction",
  "international pragmatic justice jurisdiction",
  "international impractical justice jurisdiction",
  "international feasible justice jurisdiction",
  "international infeasible justice jurisdiction",
  "international achievable justice jurisdiction",
  "international unachievable justice jurisdiction",
  "international attainable justice jurisdiction",
  "international unattainable justice jurisdiction",
  "international possible justice jurisdiction",
  "international impossible justice jurisdiction",
  "international probable justice jurisdiction",
  "international improbable justice jurisdiction",
  "international likely justice jurisdiction",
  "international unlikely justice jurisdiction",
  "international certain justice jurisdiction",
  "international uncertain justice jurisdiction",
  "international definite justice jurisdiction",
  "international indefinite justice jurisdiction",
  "international absolute justice jurisdiction",
  "international relative justice jurisdiction",
  "international objective justice jurisdiction",
  "international subjective justice jurisdiction",
  "international impartial justice jurisdiction",
  "international partial justice jurisdiction",
  "international neutral justice jurisdiction",
  "international biased justice jurisdiction",
  "international prejudiced justice jurisdiction",
  "international unprejudiced justice jurisdiction",
  "international discriminatory justice jurisdiction",
  "international non-discriminatory justice jurisdiction",
  "international equal justice jurisdiction",
  "international unequal justice jurisdiction",
  "international symmetrical justice jurisdiction",
  "international asymmetrical justice jurisdiction",
  "international reciprocal justice jurisdiction",
  "international non-reciprocal justice jurisdiction",
  "international mutual justice jurisdiction",
  "international non-mutual justice jurisdiction",
  "international cooperative justice jurisdiction",
  "international non-cooperative justice jurisdiction",
  "international collaborative justice jurisdiction",
  "international non-collaborative justice jurisdiction",
  "international coordinated justice jurisdiction",
  "international uncoordinated justice jurisdiction",
  "international harmonized justice jurisdiction",
  "international disharmonized justice jurisdiction",
  "international synchronized justice jurisdiction",
  "international unsynchronized justice jurisdiction",
  "international integrated justice jurisdiction",
  "international disintegrated justice jurisdiction",
  "international unified justice jurisdiction",
  "international disunified justice jurisdiction",
  "international consolidated justice jurisdiction",
  "international unconsolidated justice jurisdiction",
  "international merged justice jurisdiction",
  "international unmerged justice jurisdiction",
  "international combined justice jurisdiction",
  "international uncombined justice jurisdiction",
  "international joint justice jurisdiction",
  "international disjoint justice jurisdiction",
  "international shared justice jurisdiction",
  "international unshared justice jurisdiction",
  "international collective justice jurisdiction",
  "international individual justice jurisdiction",
  "international communal justice jurisdiction",
  "international personal justice jurisdiction",
  "international public justice jurisdiction",
  "international private justice jurisdiction",
  "international state justice jurisdiction",
  "international non-state justice jurisdiction",
  "international governmental justice jurisdiction",
  "international non-governmental justice jurisdiction",
  "international official justice jurisdiction",
  "international unofficial justice jurisdiction",
  "international formal justice jurisdiction",
  "international informal justice jurisdiction",
  "international institutional justice jurisdiction",
  "international non-institutional justice jurisdiction",
  "international organizational justice jurisdiction",
  "international non-organizational justice jurisdiction",
  "international systematic justice jurisdiction",
  "international unsystematic justice jurisdiction",
  "international structured justice jurisdiction",
  "international unstructured justice jurisdiction",
  "international ordered justice jurisdiction",
  "international disordered justice jurisdiction",
  "international regular justice jurisdiction",
  "international irregular justice jurisdiction",
  "international consistent justice jurisdiction",
  "international inconsistent justice jurisdiction",
  "international coherent justice jurisdiction",
  "international incoherent justice jurisdiction",
  "international logical justice jurisdiction",
  "international illogical justice jurisdiction",
  "international rational justice jurisdiction",
  "international irrational justice jurisdiction",
  "international reasonable justice jurisdiction",
  "international unreasonable justice jurisdiction",
  "international sensible justice jurisdiction",
  "international insensible justice jurisdiction",
  "international practical justice jurisdiction",
  "international impractical justice jurisdiction",
  "international pragmatic justice jurisdiction",
  "international impragmatic justice jurisdiction",
  "international realistic justice jurisdiction",
  "international unrealistic justice jurisdiction",
  "international feasible justice jurisdiction",
  "international infeasible justice jurisdiction",
  "international achievable justice jurisdiction",
  "international unachievable justice jurisdiction",
  "international attainable justice jurisdiction",
  "international unattainable justice jurisdiction",
  "international possible justice jurisdiction",
  "international impossible justice jurisdiction",
  "international probable justice jurisdiction",
  "international improbable justice jurisdiction",
  "international likely justice jurisdiction",
  "international unlikely justice jurisdiction",
  "international certain justice jurisdiction",
  "international uncertain justice jurisdiction",
  "international definite justice jurisdiction",
  "international indefinite justice jurisdiction",
  "international absolute justice jurisdiction",
  "international relative justice jurisdiction",
  "international objective justice jurisdiction",
  "international subjective justice jurisdiction",
  "international impartial justice jurisdiction",
  "international partial justice jurisdiction",
  "international neutral justice jurisdiction",
  "international biased justice jurisdiction",
  "international prejudiced justice jurisdiction",
  "international unprejudiced justice jurisdiction",
  "international discriminatory justice jurisdiction",
  "international non-discriminatory justice jurisdiction",
  "international equal justice jurisdiction",
  "international unequal justice jurisdiction",
  "international symmetrical justice jurisdiction",
  "international asymmetrical justice jurisdiction",
  "international reciprocal justice jurisdiction",
  "international non-reciprocal justice jurisdiction",
  "international mutual justice jurisdiction",
  "international non-mutual justice jurisdiction",
  "international cooperative justice jurisdiction",
  "international non-cooperative justice jurisdiction",
  "international collaborative justice jurisdiction",
  "international non-collaborative justice jurisdiction",
  "international coordinated justice jurisdiction",
  "international uncoordinated justice jurisdiction",
  "international harmonized justice jurisdiction",
  "international disharmonized justice jurisdiction",
  "international synchronized justice jurisdiction",
  "international unsynchronized justice jurisdiction",
  "international integrated justice jurisdiction",
  "international disintegrated justice jurisdiction",
  "international unified justice jurisdiction",
  "international disunified justice jurisdiction",
  "international consolidated justice jurisdiction",
  "international unconsolidated justice jurisdiction",
  "international merged justice jurisdiction",
  "international unmerged justice jurisdiction",
  "international combined justice jurisdiction",
  "international uncombined justice jurisdiction",
  "international joint justice jurisdiction",
  "international disjoint justice jurisdiction",
  "international shared justice jurisdiction",
  "international unshared justice jurisdiction",
  "international collective justice jurisdiction",
  "international individual justice jurisdiction",
  "international communal justice jurisdiction",
  "international personal justice jurisdiction",
  "international public justice jurisdiction",
  "international private justice jurisdiction",
  "international state justice jurisdiction",
  "international non-state justice jurisdiction",
  "international governmental justice jurisdiction",
  "international non-governmental justice jurisdiction",
  "international official justice jurisdiction",
  "international unofficial justice jurisdiction",
  "international formal justice jurisdiction",
  "international informal justice jurisdiction",
  "international institutional justice jurisdiction",
  "international non-institutional justice jurisdiction",
  "international organizational justice jurisdiction",
  "international non-organizational justice jurisdiction",
  "international systematic justice jurisdiction",
  "international unsystematic justice jurisdiction",
  "international structured justice jurisdiction",
  "international unstructured justice jurisdiction",
  "international ordered justice jurisdiction",
  "international disordered justice jurisdiction",
  "international regular justice jurisdiction",
  "international irregular justice jurisdiction",
  "international consistent justice jurisdiction",
  "international inconsistent justice jurisdiction",
  "international coherent justice jurisdiction",
  "international incoherent justice jurisdiction",
]

// List of non-legal keywords that indicate a query is not legal in nature
const nonLegalKeywords = [
  "math",
  "equation",
  "solve",
  "calculate",
  "computation",
  "algorithm",
  "programming",
  "code",
  "function",
  "variable",
  "loop",
  "array",
  "string",
  "integer",
  "float",
  "boolean",
  "class",
  "object",
  "method",
  "inheritance",
  "polymorphism",
  "encapsulation",
  "abstraction",
  "interface",
  "implementation",
  "compiler",
  "interpreter",
  "runtime",
  'syntax  "abstraction',
  "interface",
  "implementation",
  "compiler",
  "interpreter",
  "runtime",
  "syntax",
  "error",
  "debug",
  "physics",
  "chemistry",
  "biology",
  "astronomy",
  "geography",
  "history",
  "literature",
  "poetry",
  "fiction",
  "novel",
  "story",
  "plot",
  "character",
  "setting",
  "theme",
  "symbol",
  "metaphor",
  "simile",
  "personification",
  "alliteration",
  "assonance",
  "consonance",
  "onomatopoeia",
  "hyperbole",
  "understatement",
  "irony",
  "sarcasm",
  "paradox",
  "oxymoron",
  "pun",
  "joke",
  "riddle",
  "puzzle",
  "game",
  "sport",
  "exercise",
  "diet",
  "nutrition",
  "recipe",
  "cooking",
  "baking",
  "ingredient",
  "measurement",
  "temperature",
  "time",
  "distance",
  "speed",
  "acceleration",
  "force",
  "energy",
  "power",
  "work",
  "heat",
  "light",
  "sound",
  "electricity",
  "magnetism",
  "gravity",
  "atom",
  "molecule",
  "element",
  "compound",
  "reaction",
  "acid",
  "base",
  "salt",
  "metal",
  "nonmetal",
  "cell",
  "tissue",
  "organ",
  "system",
  "organism",
  "species",
  "genus",
  "family",
  "order",
  "class",
  "phylum",
  "kingdom",
  "domain",
  "evolution",
  "natural selection",
  "mutation",
  "adaptation",
  "ecosystem",
  "habitat",
  "niche",
  "population",
  "community",
  "biome",
  "weather",
  "climate",
  "atmosphere",
  "hydrosphere",
  "lithosphere",
  "plate tectonics",
  "earthquake",
  "volcano",
  "mountain",
  "valley",
  "plain",
  "plateau",
  "desert",
  "forest",
  "grassland",
  "tundra",
  "ocean",
  "sea",
  "lake",
  "river",
  "stream",
  "pond",
  "wetland",
  "glacier",
  "iceberg",
  "island",
  "peninsula",
  "isthmus",
  "strait",
  "bay",
  "gulf",
  "cape",
  "delta",
  "beach",
  "cliff",
  "cave",
  "canyon",
  "gorge",
  "waterfall",
  "geyser",
  "hot spring",
  "mineral",
  "rock",
  "igneous",
  "sedimentary",
  "metamorphic",
  "fossil",
  "dinosaur",
  "mammal",
  "bird",
  "reptile",
  "amphibian",
  "fish",
  "insect",
  "arachnid",
  "crustacean",
  "mollusk",
  "worm",
  "bacteria",
  "virus",
  "fungus",
  "protist",
  "algae",
  "plant",
  "flower",
  "fruit",
  "vegetable",
  "tree",
  "shrub",
  "herb",
  "grass",
  "moss",
  "fern",
  "cone",
  "seed",
  "root",
  "stem",
  "leaf",
  "flower",
  "fruit",
  "pollen",
  "nectar",
  "photosynthesis",
  "respiration",
  "transpiration",
  "germination",
  "pollination",
  "fertilization",
  "mitosis",
  "meiosis",
  "gene",
  "chromosome",
  "DNA",
  "RNA",
  "protein",
  "enzyme",
  "hormone",
  "neuron",
  "synapse",
  "reflex",
  "sense",
  "sight",
  "hearing",
  "touch",
  "taste",
  "smell",
  "balance",
  "proprioception",
  "pain",
  "pleasure",
  "emotion",
  "feeling",
  "thought",
  "memory",
  "learning",
  "intelligence",
  "consciousness",
  "subconsciousness",
  "dream",
  "sleep",
  "wake",
  "circadian rhythm",
  "biorhythm",
  "health",
  "disease",
  "illness",
  "symptom",
  "diagnosis",
  "treatment",
  "cure",
  "prevention",
  "vaccination",
  "immunization",
  "antibiotic",
  "antiviral",
  "antifungal",
  "antiseptic",
  "disinfectant",
  "sterilization",
  "hygiene",
  "sanitation",
  "nutrition",
  "diet",
  "exercise",
  "rest",
  "stress",
  "relaxation",
  "meditation",
  "yoga",
  "tai chi",
  "qigong",
  "acupuncture",
  "massage",
  "chiropractic",
  "osteopathy",
  "homeopathy",
  "naturopathy",
  "herbalism",
  "aromatherapy",
  "reflexology",
  "reiki",
  "crystal healing",
  "faith healing",
  "prayer",
  "ritual",
  "ceremony",
  "tradition",
  "culture",
  "society",
  "community",
  "family",
  "marriage",
  "divorce",
  "parent",
  "child",
  "sibling",
  "relative",
  "friend",
  "enemy",
  "ally",
  "partner",
  "colleague",
  "coworker",
  "boss",
  "employee",
  "customer",
  "client",
  "patient",
  "student",
  "teacher",
  "mentor",
  "coach",
  "trainer",
  "athlete",
  "artist",
  "musician",
  "actor",
  "dancer",
  "writer",
  "poet",
  "painter",
  "sculptor",
  "photographer",
  "filmmaker",
  "designer",
  "architect",
  "engineer",
  "scientist",
  "mathematician",
  "philosopher",
  "psychologist",
  "sociologist",
  "anthropologist",
  "archaeologist",
  "historian",
  "geographer",
  "economist",
  "political scientist",
  "linguist",
  "translator",
  "interpreter",
  "journalist",
  "reporter",
  "editor",
  "publisher",
  "broadcaster",
  "podcaster",
  "blogger",
  "vlogger",
  "influencer",
  "celebrity",
  "politician",
  "diplomat",
  "soldier",
  "sailor",
  "airman",
  "marine",
  "police officer",
  "firefighter",
  "paramedic",
  "doctor",
  "nurse",
  "pharmacist",
  "dentist",
  "veterinarian",
  "therapist",
  "counselor",
  "social worker",
  "clergy",
  "monk",
  "nun",
  "priest",
  "rabbi",
  "imam",
  "guru",
  "shaman",
  "witch",
  "wizard",
  "magician",
  "sorcerer",
  "necromancer",
  "alchemist",
  "astrologer",
  "fortune teller",
  "psychic",
  "medium",
  "channeler",
  "ghost",
  "spirit",
  "demon",
  "angel",
  "god",
  "goddess",
  "deity",
  "divinity",
  "sacred",
  "profane",
  "holy",
  "unholy",
  "blessed",
  "cursed",
  "heaven",
  "hell",
  "purgatory",
  "limbo",
  "nirvana",
  "samsara",
  "reincarnation",
  "afterlife",
  "soul",
  "spirit",
  "mind",
  "body",
  "heart",
  "brain",
  "neuron",
  "synapse",
  "thought",
  "feeling",
  "emotion",
  "sensation",
  "perception",
  "cognition",
  "metacognition",
  "consciousness",
  "subconsciousness",
  "unconsciousness",
  "dream",
  "nightmare",
  "fantasy",
  "imagination",
  "creativity",
  "innovation",
  "invention",
  "discovery",
  "exploration",
  "adventure",
  "journey",
  "quest",
  "mission",
  "goal",
  "objective",
  "purpose",
  "meaning",
  "value",
  "worth",
  "price",
  "cost",
  "benefit",
  "profit",
  "loss",
  "gain",
  "investment",
  "return",
  "dividend",
  "interest",
  "principal",
  "asset",
  "liability",
  "equity",
  "debt",
  "credit",
  "debit",
  "balance",
  "budget",
  "income",
  "expense",
  "revenue",
  "cost",
  "price",
  "value",
  "worth",
  "wealth",
  "poverty",
  "rich",
  "poor",
  "middle class",
  "working class",
  "upper class",
  "lower class",
  "socioeconomic status",
  "standard of living",
  "quality of life",
  "lifestyle",
  "fashion",
  "trend",
  "fad",
  "style",
  "design",
  "pattern",
  "texture",
  "color",
  "shape",
  "size",
  "dimension",
  "measurement",
  "scale",
  "proportion",
  "ratio",
  "fraction",
  "decimal",
  "percentage",
  "average",
  "mean",
  "median",
  "mode",
  "range",
  "variance",
  "standard deviation",
  "probability",
  "statistics",
  "data",
  "information",
  "knowledge",
  "wisdom",
  "understanding",
  "comprehension",
  "learning",
  "education",
  "training",
  "skill",
  "ability",
  "talent",
  "gift",
  "aptitude",
  "intelligence",
  "IQ",
  "EQ",
  "genius",
  "prodigy",
  "savant",
  "expert",
  "novice",
  "beginner",
  "intermediate",
  "advanced",
  "master",
  "grandmaster",
  "champion",
  "winner",
  "loser",
  "competitor",
  "rival",
  "opponent",
  "adversary",
  "enemy",
  "ally",
  "friend",
  "acquaintance",
  "stranger",
  "neighbor",
  "citizen",
  "resident",
  "immigrant",
  "emigrant",
  "refugee",
  "asylum seeker",
  "tourist",
  "traveler",
  "explorer",
  "adventurer",
  "pioneer",
  "settler",
  "colonist",
  "native",
  "indigenous",
  "aboriginal",
  "tribal",
  "nomadic",
  "sedentary",
  "urban",
  "suburban",
  "rural",
  "metropolitan",
  "cosmopolitan",
  "provincial",
  "local",
  "regional",
  "national",
  "international",
  "global",
  "universal",
  "cosmic",
  "celestial",
  "terrestrial",
  "extraterrestrial",
  "alien",
  "foreign",
  "domestic",
  "internal",
  "external",
  "intrinsic",
  "extrinsic",
  "inherent",
  "acquired",
  "innate",
  "learned",
  "conditioned",
  "instinctive",
  "reflexive",
  "automatic",
  "voluntary",
  "involuntary",
  "conscious",
  "unconscious",
  "subconscious",
  "aware",
  "unaware",
  "attentive",
  "inattentive",
  "focused",
  "distracted",
  "concentrated",
  "scattered",
  "organized",
  "disorganized",
  "ordered",
  "disordered",
  "structured",
  "unstructured",
  "systematic",
  "unsystematic",
  "methodical",
  "haphazard",
  "planned",
  "spontaneous",
  "deliberate",
  "accidental",
  "intentional",
  "unintentional",
  "purposeful",
  "purposeless",
  "meaningful",
  "meaningless",
  "significant",
  "insignificant",
  "important",
  "unimportant",
  "essential",
  "nonessential",
  "necessary",
  "unnecessary",
  "required",
  "optional",
  "mandatory",
  "voluntary",
  "compulsory",
  "discretionary",
  "obligatory",
  "elective",
  "forced",
  "chosen",
  "imposed",
  "selected",
  "assigned",
  "elected",
  "appointed",
  "nominated",
  "designated",
  "specified",
  "identified",
  "determined",
  "decided",
  "resolved",
  "settled",
  "fixed",
  "variable",
  "constant",
  "changing",
  "static",
  "dynamic",
  "stable",
  "unstable",
  "balanced",
  "imbalanced",
  "equilibrium",
  "disequilibrium",
  "harmony",
  "discord",
  "consonance",
  "dissonance",
  "agreement",
  "disagreement",
  "consensus",
  "dissent",
  "unity",
  "division",
  "whole",
  "part",
  "complete",
  "incomplete",
  "finished",
  "unfinished",
  "done",
  "undone",
  "accomplished",
  "unaccomplished",
  "achieved",
  "unachieved",
  "fulfilled",
  "unfulfilled",
  "satisfied",
  "unsatisfied",
  "content",
  "discontent",
  "happy",
  "unhappy",
  "joyful",
  "sorrowful",
  "pleased",
  "displeased",
  "delighted",
  "disappointed",
  "excited",
  "bored",
  "interested",
  "uninterested",
  "engaged",
  "disengaged",
  "involved",
  "uninvolved",
  "committed",
  "uncommitted",
  "dedicated",
  "undedicated",
  "devoted",
  "undevoted",
  "loyal",
  "disloyal",
  "faithful",
  "unfaithful",
  "trustworthy",
  "untrustworthy",
  "reliable",
  "unreliable",
  "dependable",
  "undependable",
  "consistent",
  "inconsistent",
  "steady",
  "unsteady",
  "stable",
  "unstable",
  "secure",
  "insecure",
  "safe",
  "unsafe",
  "protected",
  "unprotected",
  "sheltered",
  "exposed",
  "covered",
  "uncovered",
  "hidden",
  "revealed",
  "concealed",
  "disclosed",
  "secret",
  "public",
  "private",
  "personal",
  "impersonal",
  "intimate",
  "distant",
  "close",
  "far",
  "near",
  "remote",
  "adjacent",
  "contiguous",
  "touching",
  "separate",
  "connected",
  "linked",
  "unlinked",
  "joined",
  "disjoined",
  "united",
  "divided",
  "integrated",
  "segregated",
  "inclusive",
  "exclusive",
  "comprehensive",
  "limited",
  "extensive",
  "restricted",
  "expansive",
  "constrained",
  "broad",
  "narrow",
  "wide",
  "thin",
  "thick",
  "deep",
  "shallow",
  "high",
  "low",
  "tall",
  "short",
  "long",
  "brief",
  "big",
  "small",
  "large",
  "tiny",
  "huge",
  "minute",
  "enormous",
  "microscopic",
  "gigantic",
  "infinitesimal",
  "infinite",
  "finite",
  "eternal",
  "temporal",
  "permanent",
  "temporary",
  "enduring",
  "fleeting",
  "lasting",
  "momentary",
  "persistent",
  "transient",
  "constant",
  "variable",
  "fixed",
  "fluid",
  "rigid",
  "flexible",
  "hard",
  "soft",
  "solid",
  "liquid",
  "gas",
  "plasma",
  "matter",
  "energy",
  "space",
  "time",
  "dimension",
  "universe",
  "multiverse",
  "cosmos",
  "chaos",
  "order",
  "disorder",
  "complexity",
  "simplicity",
  "difficulty",
  "ease",
  "challenge",
  "opportunity",
  "problem",
  "solution",
  "question",
  "answer",
  "query",
  "response",
  "input",
  "output",
  "cause",
  "effect",
  "reason",
  "result",
  "premise",
  "conclusion",
  "hypothesis",
  "theory",
  "law",
  "principle",
  "rule",
  "guideline",
  "standard",
  "criterion",
  "benchmark",
  "measure",
  "metric",
  "indicator",
  "sign",
  "symbol",
  "representation",
  "abstraction",
  "concretization",
  "generalization",
  "specialization",
  "categorization",
  "classification",
  "taxonomy",
  "hierarchy",
  "network",
  "system",
  "structure",
  "function",
  "form",
  "content",
  "substance",
  "essence",
  "nature",
  "character",
  "quality",
  "quantity",
  "amount",
  "number",
  "count",
  "sum",
  "total",
  "whole",
  "part",
  "fraction",
  "segment",
  "section",
  "division",
  "unit",
  "element",
  "component",
  "constituent",
  "ingredient",
  "factor",
  "variable",
  "parameter",
  "constant",
  "coefficient",
  "term",
  "expression",
  "equation",
  "formula",
  "algorithm",
  "procedure",
  "process",
  "method",
  "technique",
  "approach",
  "strategy",
  "tactic",
  "plan",
  "scheme",
  "design",
  "blueprint",
  "model",
  "prototype",
  "template",
  "pattern",
  "example",
  "instance",
  "case",
  "scenario",
  "situation",
  "circumstance",
  "condition",
  "state",
  "status",
  "position",
  "location",
  "place",
  "space",
  "area",
  "region",
  "zone",
  "territory",
  "domain",
  "field",
  "discipline",
  "subject",
  "topic",
  "theme",
  "motif",
  "concept",
  "idea",
  "notion",
  "thought",
  "belief",
  "opinion",
  "view",
  "perspective",
  "standpoint",
  "position",
  "stance",
  "attitude",
  "approach",
  "orientation",
  "direction",
  "trend",
  "tendency",
  "inclination",
  "disposition",
  "propensity",
  "proclivity",
  "predisposition",
  "bias",
  "prejudice",
  "partiality",
  "favoritism",
  "discrimination",
  "preference",
  "choice",
  "selection",
  "option",
  "alternative",
  "possibility",
  "probability",
  "likelihood",
  "chance",
  "opportunity",
  "prospect",
  "potential",
  "capacity",
  "capability",
  "ability",
  "skill",
  "talent",
  "gift",
  "aptitude",
  "knack",
  "faculty",
  "power",
  "strength",
  "weakness",
  "advantage",
  "disadvantage",
  "benefit",
  "drawback",
  "pro",
  "con",
  "plus",
  "minus",
  "positive",
  "negative",
  "affirmative",
  "negative",
  "yes",
  "no",
  "maybe",
  "perhaps",
  "possibly",
  "probably",
  "certainly",
  "definitely",
  "absolutely",
  "relatively",
  "comparatively",
  "proportionally",
  "accordingly",
  "consequently",
  "therefore",
  "thus",
  "hence",
  "so",
  "then",
  "next",
  "subsequently",
  "afterward",
  "later",
  "earlier",
  "before",
  "after",
  "during",
  "while",
  "when",
  "where",
  "why",
  "how",
  "what",
  "who",
  "whom",
  "whose",
  "which",
  "that",
  "this",
  "these",
  "those",
  "here",
  "there",
  "now",
  "then",
  "today",
  "tomorrow",
  "yesterday",
  "soon",
  "later",
  "earlier",
  "never",
  "always",
  "sometimes",
  "occasionally",
  "rarely",
  "frequently",
  "often",
  "seldom",
  "usually",
  "normally",
  "typically",
  "generally",
  "commonly",
  "universally",
  "globally",
  "locally",
  "regionally",
  "nationally",
  "internationally",
  "worldwide",
  "everywhere",
  "nowhere",
  "somewhere",
  "anywhere",
  "everywhere",
  "here",
  "there",
  "up",
  "down",
  "left",
  "right",
  "front",
  "back",
  "top",
  "bottom",
  "side",
  "center",
  "middle",
  "edge",
  "corner",
  "surface",
  "interior",
  "exterior",
  "inside",
  "outside",
  "within",
  "without",
  "internal",
  "external",
  "intrinsic",
  "extrinsic",
  "inherent",
  "acquired",
  "natural",
  "artificial",
  "synthetic",
  "organic",
  "inorganic",
  "biological",
  "chemical",
  "physical",
  "mechanical",
  "electrical",
  "electronic",
  "digital",
  "analog",
  "virtual",
  "real",
  "actual",
  "potential",
  "theoretical",
  "practical",
  "applied",
  "pure",
  "basic",
  "fundamental",
  "advanced",
  "elementary",
  "simple",
  "complex",
  "complicated",
  "intricate",
  "elaborate",
  "sophisticated",
  "primitive",
  "rudimentary",
  "crude",
  "refined",
  "polished",
  "finished",
  "raw",
  "processed",
  "manufactured",
  "handmade",
  "custom",
  "standard",
  "typical",
  "atypical",
  "normal",
  "abnormal",
  "regular",
  "irregular",
  "ordinary",
  "extraordinary",
  "common",
  "uncommon",
  "rare",
  "frequent",
  "usual",
  "unusual",
  "strange",
  "familiar",
  "unfamiliar",
  "known",
  "unknown",
  "recognized",
  "unrecognized",
  "identified",
  "unidentified",
  "named",
  "unnamed",
  "labeled",
  "unlabeled",
  "classified",
  "unclassified",
  "categorized",
  "uncategorized",
  "organized",
  "disorganized",
  "arranged",
  "disarranged",
  "ordered",
  "disordered",
  "systematic",
  "unsystematic",
  "methodical",
  "haphazard",
  "random",
  "deliberate",
  "intentional",
  "unintentional",
  "accidental",
  "purposeful",
  "purposeless",
  "meaningful",
  "meaningless",
  "significant",
  "insignificant",
  "important",
  "unimportant",
  "essential",
  "nonessential",
  "necessary",
  "unnecessary",
  "required",
  "optional",
  "mandatory",
  "voluntary",
  "compulsory",
  "discretionary",
  "obligatory",
  "elective",
  "forced",
  "chosen",
  "imposed",
  "selected",
  "assigned",
  "elected",
  "appointed",
  "nominated",
  "designated",
  "specified",
  "identified",
  "determined",
  "decided",
  "resolved",
  "settled",
  "fixed",
  "variable",
  "constant",
  "changing",
  "static",
  "dynamic",
  "stable",
  "unstable",
  "balanced",
  "imbalanced",
  "equilibrium",
  "disequilibrium",
  "harmony",
  "discord",
  "consonance",
  "dissonance",
  "agreement",
  "disagreement",
  "consensus",
  "dissent",
  "unity",
  "division",
  "whole",
  "part",
  "complete",
  "incomplete",
  "finished",
  "unfinished",
  "done",
  "undone",
  "accomplished",
  "unaccomplished",
  "achieved",
  "unachieved",
  "fulfilled",
  "unfulfilled",
  "satisfied",
  "unsatisfied",
  "content",
  "discontent",
  "happy",
  "unhappy",
  "joyful",
  "sorrowful",
  "pleased",
  "displeased",
  "delighted",
  "disappointed",
  "excited",
  "bored",
  "interested",
  "uninterested",
  "engaged",
  "disengaged",
  "involved",
  "uninvolved",
  "committed",
  "uncommitted",
  "dedicated",
  "undedicated",
  "devoted",
  "undevoted",
  "loyal",
  "disloyal",
  "faithful",
  "unfaithful",
  "trustworthy",
  "untrustworthy",
  "reliable",
  "unreliable",
  "dependable",
  "undependable",
  "consistent",
  "inconsistent",
  "steady",
  "unsteady",
  "stable",
  "unstable",
  "secure",
  "insecure",
  "safe",
  "unsafe",
  "protected",
  "unprotected",
  "sheltered",
  "exposed",
  "covered",
  "uncovered",
  "hidden",
  "revealed",
  "concealed",
  "disclosed",
  "secret",
  "public",
  "private",
  "personal",
  "impersonal",
  "intimate",
  "distant",
  "close",
  "far",
  "near",
  "remote",
  "adjacent",
  "contiguous",
  "touching",
  "separate",
  "connected",
  "linked",
  "unlinked",
  "joined",
  "disjoined",
  "united",
  "divided",
  "integrated",
  "segregated",
  "inclusive",
  "exclusive",
  "comprehensive",
  "limited",
  "extensive",
  "restricted",
  "expansive",
  "constrained",
  "broad",
  "narrow",
  "wide",
  "thin",
  "thick",
  "deep",
  "shallow",
  "high",
  "low",
  "tall",
  "short",
  "long",
  "brief",
  "big",
  "small",
  "large",
  "tiny",
  "huge",
  "minute",
  "enormous",
  "microscopic",
  "gigantic",
  "infinitesimal",
  "infinite",
  "finite",
  "eternal",
  "temporal",
  "permanent",
  "temporary",
  "enduring",
  "fleeting",
  "lasting",
  "momentary",
  "persistent",
  "transient",
  "constant",
  "variable",
  "fixed",
  "fluid",
  "rigid",
  "flexible",
  "hard",
  "soft",
  "solid",
  "liquid",
  "gas",
  "plasma",
  "matter",
  "energy",
  "space",
  "time",
  "dimension",
  "universe",
  "multiverse",
  "cosmos",
  "chaos",
  "order",
  "disorder",
  "complexity",
  "simplicity",
  "difficulty",
  "ease",
  "challenge",
  "opportunity",
  "problem",
  "solution",
  "question",
  "answer",
  "query",
  "response",
  "input",
  "output",
  "cause",
  "effect",
  "reason",
  "result",
  "premise",
  "conclusion",
  "hypothesis",
  "theory",
  "law",
  "principle",
  "rule",
  "guideline",
  "standard",
  "criterion",
  "benchmark",
  "measure",
  "metric",
  "indicator",
  "sign",
  "symbol",
  "representation",
  "abstraction",
  "concretization",
  "generalization",
  "specialization",
  "categorization",
  "classification",
  "taxonomy",
  "hierarchy",
  "network",
  "system",
  "structure",
  "function",
  "form",
  "content",
  "substance",
  "essence",
  "nature",
  "character",
  "quality",
  "quantity",
  "amount",
  "number",
  "count",
  "sum",
  "total",
  "whole",
  "part",
  "fraction",
  "segment",
  "section",
  "division",
  "unit",
  "element",
  "component",
  "constituent",
  "ingredient",
  "factor",
  "variable",
  "parameter",
  "constant",
  "coefficient",
  "term",
  "expression",
  "equation",
  "formula",
  "algorithm",
  "procedure",
  "process",
  "method",
  "technique",
  "approach",
  "strategy",
  "tactic",
  "plan",
  "scheme",
  "design",
  "blueprint",
  "model",
  "prototype",
  "template",
  "pattern",
  "example",
  "instance",
  "case",
  "scenario",
  "situation",
  "circumstance",
  "condition",
  "state",
  "status",
  "position",
  "location",
  "place",
  "space",
  "area",
  "region",
  "zone",
  "territory",
  "domain",
  "field",
  "discipline",
  "subject",
  "topic",
  "theme",
  "motif",
  "concept",
  "idea",
  "notion",
  "thought",
  "belief",
  "opinion",
  "view",
  "perspective",
  "standpoint",
  "position",
  "stance",
  "attitude",
  "approach",
  "orientation",
  "direction",
  "trend",
  "tendency",
  "inclination",
  "disposition",
  "propensity",
  "proclivity",
  "predisposition",
  "bias",
  "prejudice",
  "partiality",
  "favoritism",
  "discrimination",
  "preference",
  "choice",
  "selection",
  "option",
  "alternative",
  "possibility",
  "probability",
  "likelihood",
  "chance",
  "opportunity",
  "prospect",
  "potential",
  "capacity",
  "capability",
  "ability",
  "skill",
  "talent",
  "gift",
  "aptitude",
  "knack",
  "faculty",
  "power",
  "strength",
  "weakness",
  "advantage",
  "disadvantage",
  "benefit",
  "drawback",
  "pro",
  "con",
  "plus",
  "minus",
  "positive",
  "negative",
  "affirmative",
  "negative",
  "yes",
  "no",
  "maybe",
  "perhaps",
  "possibly",
  "probably",
  "certainly",
  "definitely",
  "absolutely",
  "relatively",
  "comparatively",
  "proportionally",
  "accordingly",
  "consequently",
  "therefore",
  "thus",
  "hence",
  "so",
  "then",
  "next",
  "subsequently",
  "afterward",
  "later",
  "earlier",
  "before",
  "after",
  "during",
  "while",
  "when",
  "where",
  "why",
  "how",
  "what",
  "who",
  "whom",
  "whose",
  "which",
  "that",
  "this",
  "these",
  "those",
  "here",
  "there",
  "now",
  "then",
  "today",
  "tomorrow",
  "yesterday",
  "soon",
  "later",
  "earlier",
  "never",
  "always",
  "sometimes",
  "occasionally",
  "rarely",
  "frequently",
  "often",
  "seldom",
  "usually",
  "normally",
  "typically",
  "generally",
  "commonly",
  "universally",
  "globally",
  "locally",
  "regionally",
  "nationally",
  "internationally",
  "worldwide",
  "everywhere",
  "nowhere",
  "somewhere",
  "anywhere",
  "everywhere",
  "here",
  "there",
  "up",
  "down",
  "left",
  "right",
  "front",
  "back",
  "top",
  "bottom",
  "side",
  "center",
  "middle",
  "edge",
  "corner",
  "surface",
  "interior",
  "exterior",
  "inside",
  "outside",
  "within",
  "without",
  "internal",
  "external",
  "intrinsic",
  "extrinsic",
  "inherent",
  "acquired",
  "natural",
  "artificial",
  "synthetic",
  "organic",
  "inorganic",
  "biological",
  "chemical",
  "physical",
  "mechanical",
  "electrical",
  "electronic",
  "digital",
  "analog",
  "virtual",
  "real",
  "actual",
  "potential",
  "theoretical",
  "practical",
  "applied",
  "pure",
  "basic",
  "fundamental",
  "advanced",
  "elementary",
  "simple",
  "complex",
  "complicated",
  "intricate",
  "elaborate",
  "sophisticated",
  "primitive",
  "rudimentary",
  "crude",
  "refined",
  "polished",
  "finished",
  "raw",
  "processed",
  "manufactured",
  "handmade",
  "custom",
  "standard",
  "typical",
  "atypical",
  "normal",
  "abnormal",
  "regular",
  "irregular",
  "ordinary",
  "extraordinary",
  "common",
  "uncommon",
  "rare",
  "frequent",
  "usual",
  "unusual",
  "strange",
  "familiar",
  "unfamiliar",
  "known",
  "unknown",
  "recognized",
  "unrecognized",
  "identified",
  "unidentified",
  "named",
  "unnamed",
  "labeled",
  "unlabeled",
  "classified",
  "unclassified",
  "categorized",
  "uncategorized",
  "organized",
  "disorganized",
  "arranged",
  "disarranged",
  "ordered",
  "disordered",
  "systematic",
  "unsystematic",
  "methodical",
  "haphazard",
  "random",
  "deliberate",
  "intentional",
  "unintentional",
  "accidental",
  "purposeful",
  "purposeless",
  "meaningful",
  "meaningless",
  "significant",
  "insignificant",
  "important",
  "unimportant",
  "essential",
  "nonessential",
  "necessary",
  "unnecessary",
  "required",
  "optional",
  "mandatory",
  "voluntary",
  "compulsory",
  "discretionary",
  "obligatory",
  "elective",
]

// Function to check if a query is legal in nature
function isLegalQuery(query: string): boolean {
  // Convert query to lowercase for case-insensitive matching
  const lowercaseQuery = query.toLowerCase()

  // Check for non-legal keywords first (stronger signal)
  for (const keyword of nonLegalKeywords) {
    if (lowercaseQuery.includes(keyword.toLowerCase())) {
      return false
    }
  }

  // Check for legal keywords
  for (const keyword of legalKeywords) {
    if (lowercaseQuery.includes(keyword.toLowerCase())) {
      return true
    }
  }

  // If no legal keywords found, check if it's a general question
  // about law, legal advice, or rights
  if (
    lowercaseQuery.includes("law") ||
    lowercaseQuery.includes("legal") ||
    lowercaseQuery.includes("right") ||
    lowercaseQuery.includes("rights") ||
    lowercaseQuery.includes("court") ||
    lowercaseQuery.includes("lawyer")
  ) {
    return true
  }

  // Default to false if no legal keywords found
  return false
}

export async function POST(request: NextRequest) {
  try {
    const { query } = await request.json()

    if (!query) {
      return NextResponse.json({ error: "No query provided" }, { status: 400 })
    }

    // Check if the query is legal in nature
    if (!isLegalQuery(query)) {
      return NextResponse.json({
        response:
          "I'm a legal assistant designed to help with law-related questions. Please ask me about legal topics, rights, or legal procedures instead of general knowledge questions.",
      })
    }

    // Prepare the prompt for Gemini with legal context
    const systemPrompt =
      "You are JusticeAlly, an AI legal assistant. Provide helpful, accurate, and concise legal information in a clean, professional format. " +
      "Do not use asterisks, bold formatting, or excessive disclaimers. Present information in a straightforward manner with proper paragraphing and minimal formatting. " +
      "Include only a brief, single-line disclaimer at the end if necessary. Focus on explaining legal concepts in simple terms and providing direct, actionable information."

    // Call Gemini API
    const response = await fetch(`${GEMINI_API_URL}?key=${API_KEY}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: systemPrompt }, { text: query }],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topP: 0.95,
          maxOutputTokens: 2048, // Increased token limit for document simplification
        },
      }),
    })

    if (!response.ok) {
      const errorData = await response.json()
      console.error("Gemini API error:", errorData)
      return NextResponse.json({ error: "Failed to get response from AI" }, { status: 500 })
    }

    const data = await response.json()
    const aiResponse = data.candidates[0].content.parts[0].text

    return NextResponse.json({ response: aiResponse })
  } catch (error) {
    console.error("Error in chat API:", error)
    return NextResponse.json({ error: "Failed to process request" }, { status: 500 })
  }
}
